name: skyfresh
description: SKYfresh - Fresh fruits and juices
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^8.0.1
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  shared_preferences: ^2.5.5
  cached_network_image: ^3.3.1
  provider: ^6.1.1
  geolocator: ^14.0.3
  geocoding: ^5.0.0
  url_launcher: ^6.3.1
  razorpay_flutter: ^1.4.5
  flutter_secure_storage: 10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true